### PR TITLE
feature: Implement a fucking outstanding function

### PR DESCRIPTION
**Pull request by daicamangdeplao**

### CODE REVIEW

**Comment by daicamangdeplao** [comment]
Hello baby

**Comment by phandat1991** [comment]
Why would I merge this?

**Comment by daicamangdeplao** [comment]
Cause it is the most outstanding function ever!

**Comment by phandat1991** [comment]
But what the fucking usefulness can it be for this repository?

**Comment by phandat1991** [comment]
Anyway, just for your happiness, I merged your commit

**Pull request merged**
